// User
export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const BORRAR_USER = "BORRAR_USER";
// Auth
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
// Tarjeta
export const GET_TARJETAS = "GET_TARJETAS";
export const CARGANDO_TARJETAS = "CARGANDO_TARJETAS";
export const AGREGAR_TARJETA = "AGREGAR_TARJETA";
export const AGREGAR_TARJETA_AMARILLA = "AGREGAR_TARJETA_AMARILLA";
export const CERRAR_TARJETA = "CERRAR_TARJETA";
export const EDITAR_TARJETA = "EDITAR_TARJETA";
export const CERRAR_TARJETA_AMARILLA = "CERRAR_TARJETA_AMARILLA";
export const BORRAR_TARJETA = "BORRAR_TARJETA";
// Filter
export const GET_FILTERS = "GET_FILTERS";
export const CARGANDO_FILTERS = "CARGANDO_FILTERS";
export const AGREGAR_FILTER = "AGREGAR_FILTER";
// Campos
export const GET_CAMPOS = "GET_CAMPOS";
export const CARGANDO_CAMPOS = "CARGANDO_CAMPOS";
export const AGREGAR_CAMPOS = "AGREGAR_CAMPOS";
export const PARTE_MAQUINA = "PARTE_MAQUINA";
export const PARTE_MAQUINA_DELETE = "PARTE_MAQUINA_DELETE";
export const BORRAR_CAMPO = "BORRAR_CAMPO";
